const TIPO_FIJO = {
  SISTEMA: 1,
  DECIMAL: 2,
  ENTERO: 3,
  SELECCION: 4,
  LISTA: 5,
  TABLA: 6,
  SECCION: 7,
  TEXTO_LIBRE: 8,
  IMAGEN: 9,
};

const TIPO_DATO = {
  NUMERICO: 1,
  DECIMAL: 2,
  LISTA_VALORES: 4,
  TEXTO: 5,
  FECHA: 8,
  LOGICO: 10,
  CALCULADO: 11,
  TEXTO_LARGO: 17,
};

const OMITIR_RUBRICAS_ESTRUCTURA = new Set([
  'DATOS PERSONALES', 'DATOS GENERALES', 'DATOS BASICOS', 'INFORMACION GENERAL',
  'DATOS DE LA ATENCION', 'INFORMACION DE LA ATENCION', 'RIPS CONSULTA', 'DIAGNOSTICO'
]);
module.exports = { OMITIR_RUBRICAS_ESTRUCTURA, TIPO_FIJO, TIPO_DATO };
